### ISSUE TITLE
How to get the Map instance?

### ISSUE THREAD

**Issue by keremnymn** [shishkin/solid-maplibre#161]
Hi,

I want to get the map instance so I can use Maplibre functions on the map instance such as `getLayer`. However, the `ref` object always returns `undefined`.

```
function App() {
  let map: any;
  let test: any;

  onMount(() => {
    console.log("test: ", test)
    console.log("map: ", map)
  })
  return (
    <>
      <p ref={test}>test</p>
      <Map
        ref={map}
        style={{
          width: "100%",
          "aspect-ratio": "calc(16/9)",
        }}
        options={{
          center: [11.40416, 47.26475],
          style: mapStyle as StyleSpecification
        }}
      />
    </>
  );
}
```
Output:
```
test:  <p>
map:  undefined
```
Or maybe there's a better way to achieve this?

**Comment by shishkin** [comment]
Yes, there is `useMap` and `useMapEffect` helper functions for that. See how they're [used in Layer](https://github.com/shishkin/solid-maplibre/blob/b7777c9a5e5877a4c3f9533dc02dab9964e58ac0/src/layer.tsx#L21C1-L30). `ref` is meant to return DOM elements, so it makes less sense for the Maplibre instance.

Let me know if that works for you.
