### ISSUE TITLE
Sync Maps example doesn't work

### ISSUE THREAD

**Issue by joelmellon** [shishkin/solid-maplibre#166]
On the [examples page](https://gis-hub.gitbook.io/solid-map-gl/examples), there's an example called [Sync Maps](https://stackblitz.com/edit/solid-map-gl-sync?embed=1&file=src%2Findex.tsx). It doesn't work.

[Swipe Maps](https://stackblitz.com/edit/solid-map-gl-swipe?embed=1&file=src%2Findex.tsx) looks very similar, and also doesn't work.

The maps simply don't update each other.

**Comment by shishkin** [comment]
@joelmellon I think you mistake this project for https://github.com/GIShub4/solid-map-gl/. Please see supported examples in [here](https://github.com/shishkin/solid-maplibre/tree/main/examples).

**Comment by joelmellon** [comment]
My apologies. 🤦 I had it up in another tab.

While I have you here...have you considered adding support for [mapbox-gl-draw](https://github.com/mapbox/mapbox-gl-draw)?

**Comment by shishkin** [comment]
I didn't have a use case for it myself. However, [mapbox-gl-draw works](https://maplibre.org/maplibre-gl-js/docs/examples/mapbox-gl-draw/) with maplibre as a plugin and it should be possible to add as a separate solid component inside the map context.
