### ISSUE TITLE
Decouple Context Provider and Map Renderer

### ISSUE THREAD

**Issue by sachaw** [shishkin/solid-maplibre#58]
Stumbled across your lib and so far it's working great.

One issue I'm running into is being able to access the map object from outside of the `Map` Component.
react-map-gl have achieved this (https://visgl.github.io/react-map-gl/docs/api-reference/map-provider)
I was wondering how feasible it is for this lib or another workaround.

Thanks.

**Comment by shishkin** [comment]
Thanks for submitting the issue. Indeed, that would be useful to have. I will look into it. However if you're willing to submit a pull request, you're more than welcome!

**Comment by shishkin** [comment]
@sachaw I hope this should work in 0.3.0 now. Please let me know if it solves it for you.
